name: Auto Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  notify-render:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}